server:
  port: 8181
spring:
  application:
    name: gateway-server

  cloud:
    gateway:
      routes:
      - id: service-product
        #uri: http://127.0.0.1:9001
        uri: lb://service-product #lb代表从注册中心获取服务,根据服务名称获取地址
        predicates:
          - Path=/service-product/**
        filters:
        - RewritePath=/service-product/(?<segment>.*),/$\{segment}
#        - name: RequestRateLimiter
#          args:
#            key-resolver: '#{@userKeyResolver}'
#            redis-rate-limiter.burstCapacicy: 3
#            redis-rate-limiter.replenishRate: 1
#      discovery:
#        locator:
#          enabled: true #根据微服务名称自动转发(有了它就不需要:RewritePath)
#          lower-case-service-id: true # 将微服务的名称转为小写

  redis:
    port: 6379
    host: localhost
eureka:
  instance:
    #使用ip地址注册
    prefer-ip-address: true
    # 向注册中心注册服务id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # eureka服务地址
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/