server:
  port: 9000
spring:
  application:
    name: eureka_server

eureka:
#  instance:
#    hostname: localhost
  client:
    service-url:
      # 暴露给eureka客户端的请求地址
      defaultZone: http://127.0.0.1:8000/eureka/
      # 是否将自己注册到注册中心
    register-with-eureka: true
    # 是否从eureka中获取配置信息
    fetch-registry: true
  server:
    # 关闭eureka的自我保护机制,默认为true,生产要默认的配置即可
    enable-self-preservation: false
    # 剔除服务间隔:生产要默认的配置即可
    eviction-interval-timer-in-ms: 5000