server:
  port: 10000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/itcomon/config.git
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  instance:
    #使用ip地址注册
    prefer-ip-address: true
    # 向注册中心注册服务id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # eureka服务地址
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
