server:
  port: 9001
spring:
  application:
    name: service-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sfdb?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jpa:
    database: MySQL
    show-sql: true
    open-in-view: true
  zipkin:
    sender:
      type: rabbit
    base-url: http://127.0.0.1/9411
  sleuth:
    sampler:
      probability: 1.0
  rabbitmq:
    username: guest
    password: guest
    listener:
      direct:
        # 重试策略
        retry:
          enabled: true
      simple:
        retry:
          enabled: true
    host: localhost
    port: 5672
eureka:
  instance:
    #使用ip地址注册
    prefer-ip-address: true
    # 向注册中心注册服务id
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      # eureka服务地址
      defaultZone: http://localhost:9000/eureka/,http://localhost:8000/eureka/
